server:
  port: 8081


spring:
  application:
    name: specialty-market
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/someone?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: H03089611.
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: MyHikari
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 8.129.126.4
    port: 26379
    database: 6
    password: gcs123

#mybatis-plus 配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


appid: wx855a4cd1717292bd
appsecret: 645156b56330646944848f30a09468ce